### ISSUE TITLE
citations_per_year is empty in JSON

### ISSUE THREAD

**Issue by RohitChattopadhyay** [fredrike/googlescholar-api#1]
http://cse.bth.se/~fer/googlescholar.php?user=yI6xE0YAAAAJ

**Comment by fredrike** [comment]
Thanks for finding this. Feel free to submit a patch to fix it :smiley:

**Comment by arunhpatil** [comment]
Hi, for "citations_per_year" you can replace the loop with the following, it works: 
/*
This function was not necessary.
function iconv($a, $b, $c) {
	return $c;
}*/

$s = " \"citations_per_year\": {";
$years = $html->find('.gsc_g_t');
$scores = $html->find('.gsc_g_al');
foreach($scores as $key => $score) {
	$s .= "\n  \"" . $years[$key]->plaintext ."\": ". $score->plaintext . ",";
}
print substr($s, 0, -1) . "\n },\n";

Cheers.

**Comment by RohitChattopadhyay** [comment]
@arunhpatil , please send a pull request. I don't have much experience in PHP

**Comment by arunhpatil** [comment]
@RohitChattopadhyay, I will do that in time. In the meanwhile, you can find the code here https://github.com/arunhpatil/GoogleScholar and example: http://www.inhouseprotocols.com/publications.php. Hope this helps. 

Cheers.
